# frozen_string_literal: true

# Versions mirror NUTFes/group-manager-2 api/Gemfile(.lock) so the integration
# can be ported as-is. Only the gems relevant to authentication are kept.
source 'https://rubygems.org'

ruby '3.0.7'

gem 'devise'
gem 'devise_token_auth'
gem 'puma', '~> 4.1'
gem 'rack-cors'
gem 'rails', '~> 6.1.3.1'
gem 'sqlite3', '~> 1.4'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
